name: Windows - LiteManager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/khaled6mmd/LM-Windows-Github-RDP/main/down.bat" -OutFile "down.bat"
          if (Test-Path "down.bat") {
            Write-Output "down.bat successfully downloaded."
            cmd /c down.bat
          } else {
            Write-Error "Failed to download down.bat"
            exit 1
          }

      - name: Connect to LiteManager
        run: |
          if (Test-Path "show.bat") {
            Write-Output "Executing show.bat..."
            cmd /c show.bat
          } else {
            Write-Error "show.bat not found!"
            exit 1
          }

      - name: Time Counter
        run: |
          if (Test-Path "loop.bat") {
            Write-Output "Executing loop.bat..."
            cmd /c loop.bat
          } else {
            Write-Error "loop.bat not found!"
            exit 1
          }
